# ================
# ROOT PIPELINE
# ================

stages:
  - build
  - dockerbuild
  - promote
  - trigger_cd

include:
  - project: 'epay/devops/ci-templates'
    ref: feature/CIfrontend
    file: 'ci/release/version.yml'

  - project: 'epay/devops/ci-templates'
    ref: feature/CIfrontend
    file: 'cd/helm/services.yml'

  # ⚠️ IMPORTANT: dynamic.yml MUST COME LAST
  - project: 'epay/devops/ci-templates'
    ref: feature/CIfrontend
    file: 'templates/fe/dynamic.yml'
